const BooksData=[
    {
_id:'1',
name:'Organic',
author:'Al-aziz',
price: '10',
postKind:"For-sale",
bookCondition:"Ok",
contactMethod:"Phone",
contact:"+923123456789",
country:'Dubai',
university: 'COMSATS Univeristy Islamabad',
subject: 'Chemistry',
feature: 'Featured',
status:"Pending",
date:"25/10/2020"
},
{
_id:'2',
name:'Organic',
author:'Al-aziz',
price: '10',
postKind:"For-sale",
bookCondition:"Ok",
contactMethod:"Phone",
contact:"+923123456789",
country:'Dubai',
university: 'COMSATS Univeristy Islamabad',
subject: 'Chemistry',
feature: 'Featured',
status:"Pending",
date:"25/10/2020"
},
{
_id:'3',
name:'Organic',
author:'Al-aziz',
price: '10',
postKind:"For-sale",
bookCondition:"Ok",
contactMethod:"Phone",
contact:"+923123456789",
country:'Dubai',
university: 'COMSATS Univeristy Islamabad',
subject: 'Chemistry',
feature: 'Non-Featured',
status:"Pending",
date:"25/10/2020"
},
{
_id:'4',
name:'Organic',
author:'Al-aziz',
price: '10',
postKind:"For-sale",
bookCondition:"Ok",
contactMethod:"Phone",
contact:"+923123456789",
country:'Dubai',
university: 'COMSATS Univeristy Islamabad',
subject: 'Chemistry',
feature: 'Non-Featured',
status:"Pending",
date:"25/10/2020"
},
]

export default BooksData;