const SubjectCommentData = [
    {
        _id: '1',
        comment: 'This is Comment',
        country: 'Dubai',
        university: 'COMSATS Univeristy Islamabad',
        college: 'Al-Falah College',
        subject: "Chem",
        grade: "A",
        year: "2020",
        rating: "Good",
        hardness: "Impossible",
        teachingStyle: "Both",
        attendance: "Takes",
        homework: "Gives",
        projects: "Gives",
        curve: "Gives",
        tags: "Well, Good",
        examFrom: "Books",
        takeWithHim: "Yes",
        reference: "Facebook",
        date: "25/10/2020",
        status: "Accepted"
    },
    {
        _id: '2',
        comment: 'This is Comment',
        country: 'Dubai',
        university: 'COMSATS Univeristy Islamabad',
        college: 'Al-Falah College',
        professor: "Rafiq",
        subject: "Chem",
        grade: "A",
        year: "2020",
        rating: "Good",
        hardness: "Impossible",
        teachingStyle: "Both",
        attendance: "Takes",
        homework: "Gives",
        projects: "Gives",
        curve: "Gives",
        tags: "Well, Good",
        examFrom: "Books",
        takeWithHim: "Yes",
        reference: "Facebook",
        date: "25/10/2020",
        status: "Accepted"
    },
    {
        _id: '3',
        comment: 'This is Comment',
        country: 'Dubai',
        university: 'COMSATS Univeristy Islamabad',
        college: 'Al-Falah College',
        subject: "Chem",
        grade: "A",
        year: "2020",
        rating: "Good",
        hardness: "Impossible",
        teachingStyle: "Both",
        attendance: "Takes",
        homework: "Gives",
        projects: "Gives",
        curve: "Gives",
        tags: "Well, Good",
        examFrom: "Books",
        takeWithHim: "Yes",
        reference: "Facebook",
        date: "25/10/2020",
        status: "Accepted"
    },
    {
        _id: '4',
        comment: 'This is Comment',
        country: 'Dubai',
        university: 'COMSATS Univeristy Islamabad',
        college: 'Al-Falah College',
        subject: "Chem",
        grade: "A",
        year: "2020",
        rating: "Good",
        hardness: "Impossible",
        teachingStyle: "Both",
        attendance: "Takes",
        homework: "Gives",
        projects: "Gives",
        curve: "Gives",
        tags: "Well, Good",
        examFrom: "Books",
        takeWithHim: "Yes",
        reference: "Facebook",
        date: "25/10/2020",
        status: "Accepted"
    },
]

export default SubjectCommentData;